<a href="https://colab.research.google.com/github/Fernandomastre32/Extracion_de_conocimiento_BD/blob/main/LAB_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

al chile no se nd

In [ ]:
#Conjunto de datos\
datos = {
    "usuario": ["Ana", "felipe", "Martha", "Calorina", "Sofia", "pedro", "diego", "pepe"],
    "edad": [122, 32, 32, 32,45,45,12, 66],
    "ciudad": ["CDMX", "Monterrey", "Guadalajara", "puebla", "cancun", "merida", "tijuana", "CDMX"],
    "compras realizadas": [12, 13, 14, 14, 43, 43, 55, 66],
    "Activo": [True, False, True, True, False, True, False, True],
    "Fecha Registro": ["2026-01-12", "2026-01-2", "2026-01-3", "2026-01-5", "2026-01-6", "2026-01-11", "2026-04-12", "2026-05-12"]
    }

In [ ]:
df = pd.DataFrame(datos)

In [ ]:
print(df)

    usuario  edad       ciudad  compras realizadas  Activo Fecha Registro
0       Ana   122         CDMX                  12    True     2026-01-12
1    felipe    32    Monterrey                  13   False      2026-01-2
2    Martha    32  Guadalajara                  14    True      2026-01-3
3  Calorina    32       puebla                  14    True      2026-01-5
4     Sofia    45       cancun                  43   False      2026-01-6
5     pedro    45       merida                  43    True     2026-01-11
6     diego    12      tijuana                  55   False     2026-04-12
7      pepe    66         CDMX                  66    True     2026-05-12

In [ ]:
df.head()

    usuario  edad       ciudad  compras realizadas  Activo Fecha Registro
0       Ana   122         CDMX                  12    True     2026-01-12
1    felipe    32    Monterrey                  13   False      2026-01-2
2    Martha    32  Guadalajara                  14    True      2026-01-3
3  Calorina    32       puebla                  14    True      2026-01-5
4     Sofia    45       cancun                  43   False      2026-01-6

In [ ]:
cantidad = 1000000

In [ ]:
import random

In [ ]:
#Datos aleatorios
nombres = ["Ana", "Luis", "Martha", "Carolina", "Sofía", "Pedro", "Elena", "Diego"]
ciudades = ["CDMX", "Monterrey", "Guadalajara", "Puebla", "Cancún", "Merida", "Tijuana", "Toluca"]
categorias = ["Tecnologías", "Ropa", "Hogar", "Videojuegos", "Deportes", "Calzado", "Cosmeticos", "Infantil"]

In [ ]:
dMilton = pd.DataFrame ({
    "nombre" : [random.choice(nombres) for _ in range(cantidad)],
    "ciudad" : [random.choice(ciudades) for _ in range(cantidad)],
    "categoria" : [random.choice(categorias) for _ in range(cantidad)],
    "edad" : [random.randint(18,70) for _ in range(cantidad)],
    "salario" : [round(random.uniform(5000, 50000), 2) for _ in range (cantidad)],
    "activo" : [random.choice([True,False]) for _ in range(cantidad)],
    "anio_registro" : [random.randint(2020,2026) for _ in range(cantidad)],

})

In [ ]:
dMilton.memory_usage(deep = True)

Index                 132
nombre           56128181
ciudad           57874429
categoria        59007089
edad              8000000
salario           8000000
activo            1000000
anio_registro     8000000
dtype: int64

In [ ]:
dMilton.memory_usage(deep = True).sum() /1024**2

np.float64(188.8368902206421)